spring.application.name=task-tracker

# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/tasktracker
spring.datasource.username=postgres
spring.datasource.password=postgres

#JPA prop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.mapper.accept-case-insensitive-enums=true